apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-kyverno
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/andregri/argocd-kyverno.git
      revision: HEAD
      files:
      - path: "appset-helm/config/**/config.json"
  template:
    metadata:
      name: 'kyverno-{{ env }}'
    spec:
      project: kyverno
      source:
        repoURL: https://github.com/andregri/argocd-kyverno.git
        targetRevision: main
        path: "appset-helm/app"
      ignoreDifferences:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
        jsonPointers:
          - /rules
      destination:
        server: https://kubernetes.default.svc
        namespace: kyverno
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true